/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.accel;
import linkjvm.jni.sensors.ShortSensor;
public class AccelZ extends ShortSensor {
  private long swigCPtr;

  protected AccelZ(long cPtr, boolean cMemoryOwn) {
    super(linkjvm_accelJNI.AccelZ_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AccelZ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_accelJNI.delete_AccelZ(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public short value() {
    return linkjvm_accelJNI.AccelZ_value(swigCPtr, this);
  }

  public AccelZ() {
    this(linkjvm_accelJNI.new_AccelZ(), true);
  }

}
