/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.buttons;

public class linkjvm_buttons {
  public static void setA(IdButton value) {
    linkjvm_buttonsJNI.A_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getA() {
    long cPtr = linkjvm_buttonsJNI.A_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setB(IdButton value) {
    linkjvm_buttonsJNI.B_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getB() {
    long cPtr = linkjvm_buttonsJNI.B_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setC(IdButton value) {
    linkjvm_buttonsJNI.C_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getC() {
    long cPtr = linkjvm_buttonsJNI.C_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setX(IdButton value) {
    linkjvm_buttonsJNI.X_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getX() {
    long cPtr = linkjvm_buttonsJNI.X_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setY(IdButton value) {
    linkjvm_buttonsJNI.Y_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getY() {
    long cPtr = linkjvm_buttonsJNI.Y_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setZ(IdButton value) {
    linkjvm_buttonsJNI.Z_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getZ() {
    long cPtr = linkjvm_buttonsJNI.Z_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setSide(IdButton value) {
    linkjvm_buttonsJNI.Side_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getSide() {
    long cPtr = linkjvm_buttonsJNI.Side_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static SWIGTYPE_p_p_IdButton getAll() {
    long cPtr = linkjvm_buttonsJNI.all_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_IdButton(cPtr, false);
  }

}
