/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.buttons;

public class linkjvm_buttonsJNI {
  public final static native void AbstractButton_waitUntilClicked(long jarg1, AbstractButton jarg1_);
  public final static native void delete_AbstractButton(long jarg1);
  public final static native void AbstractButton_setPressed(long jarg1, AbstractButton jarg1_, boolean jarg2);
  public final static native boolean AbstractButton_isPressed(long jarg1, AbstractButton jarg1_);
  public final static native boolean AbstractButton_isNotPressed(long jarg1, AbstractButton jarg1_);
  public final static native boolean AbstractButton_isClicked(long jarg1, AbstractButton jarg1_);
  public final static native void AbstractButton_waitUntilReleased(long jarg1, AbstractButton jarg1_);
  public final static native void AbstractButton_waitUntilPressed(long jarg1, AbstractButton jarg1_);
  public final static native void delete_AbstractTextButton(long jarg1);
  public final static native void AbstractTextButton_setText(long jarg1, AbstractTextButton jarg1_, String jarg2);
  public final static native String AbstractTextButton_text(long jarg1, AbstractTextButton jarg1_);
  public final static native boolean AbstractTextButton_isTextDirty(long jarg1, AbstractTextButton jarg1_);
  public final static native void AbstractTextButton_resetText(long jarg1, AbstractTextButton jarg1_);
  public final static native long new_IdButton(int jarg1, String jarg2);
  public final static native void delete_IdButton(long jarg1);
  public final static native void IdButton_setText(long jarg1, IdButton jarg1_, String jarg2);
  public final static native String IdButton_text(long jarg1, IdButton jarg1_);
  public final static native boolean IdButton_isTextDirty(long jarg1, IdButton jarg1_);
  public final static native void IdButton_setPressed(long jarg1, IdButton jarg1_, boolean jarg2);
  public final static native boolean IdButton_value(long jarg1, IdButton jarg1_);
  public final static native void IdButton_resetText(long jarg1, IdButton jarg1_);
  public final static native void ExtraButtons_show();
  public final static native void ExtraButtons_hide();
  public final static native void ExtraButtons_setShown(boolean jarg1);
  public final static native boolean ExtraButtons_isShown();
  public final static native long new_ExtraButtons();
  public final static native void delete_ExtraButtons(long jarg1);
  public final static native void A_set(long jarg1, IdButton jarg1_);
  public final static native long A_get();
  public final static native void B_set(long jarg1, IdButton jarg1_);
  public final static native long B_get();
  public final static native void C_set(long jarg1, IdButton jarg1_);
  public final static native long C_get();
  public final static native void X_set(long jarg1, IdButton jarg1_);
  public final static native long X_get();
  public final static native void Y_set(long jarg1, IdButton jarg1_);
  public final static native long Y_get();
  public final static native void Z_set(long jarg1, IdButton jarg1_);
  public final static native long Z_get();
  public final static native void Side_set(long jarg1, IdButton jarg1_);
  public final static native long Side_get();
  public final static native long all_get();
  public final static native long AbstractButton_SWIGUpcast(long jarg1);
  public final static native long AbstractTextButton_SWIGUpcast(long jarg1);
  public final static native long IdButton_SWIGUpcast(long jarg1);
}
