/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.datalog;

public class DataLog {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataLog(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataLog obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_datalogJNI.delete_DataLog(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Category category(String name) {
    long cPtr = linkjvm_datalogJNI.DataLog_category(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Category(cPtr, false);
  }

  public void removeCategory(String name) {
    linkjvm_datalogJNI.DataLog_removeCategory(swigCPtr, this, name);
  }

  public SWIGTYPE_p_std__vectorT_Category_p_t categories() {
    return new SWIGTYPE_p_std__vectorT_Category_p_t(linkjvm_datalogJNI.DataLog_categories(swigCPtr, this), true);
  }

  public boolean write(DataLogWriter writer) {
    return linkjvm_datalogJNI.DataLog_write(swigCPtr, this, DataLogWriter.getCPtr(writer), writer);
  }

  public void clear() {
    linkjvm_datalogJNI.DataLog_clear(swigCPtr, this);
  }

  public DataLog() {
    this(linkjvm_datalogJNI.new_DataLog(), true);
  }

}
