/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni;

public class Battery {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Battery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Battery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_Battery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean isCharging() {
    return LinkJVMJNI.Battery_isCharging();
  }

  public static float powerLevel() {
    return LinkJVMJNI.Battery_powerLevel();
  }

  public Battery() {
    this(LinkJVMJNI.new_Battery(), true);
  }

}
