/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni;

public class ConfigPath {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConfigPath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigPath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_ConfigPath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String extension() {
    return LinkJVMJNI.ConfigPath_extension();
  }

  public static void setBasePath(String path) {
    LinkJVMJNI.ConfigPath_setBasePath(path);
  }

  public static String path(String name) {
    return LinkJVMJNI.ConfigPath_path__SWIG_0(name);
  }

  public static String path() {
    return LinkJVMJNI.ConfigPath_path__SWIG_1();
  }

  public static String defaultPath() {
    return LinkJVMJNI.ConfigPath_defaultPath();
  }

  public static String defaultConfigPath() {
    return LinkJVMJNI.ConfigPath_defaultConfigPath();
  }

  public static void setDefaultConfigPath(String name) {
    LinkJVMJNI.ConfigPath_setDefaultConfigPath(name);
  }

  public ConfigPath() {
    this(LinkJVMJNI.new_ConfigPath(), true);
  }

}
