/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni;

public class CsvWriter extends DataLogWriter {
  private long swigCPtr;

  protected CsvWriter(long cPtr, boolean cMemoryOwn) {
    super(LinkJVMJNI.CsvWriter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsvWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_CsvWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CsvWriter(SWIGTYPE_p_std__string path) {
    this(LinkJVMJNI.new_CsvWriter(SWIGTYPE_p_std__string.getCPtr(path)), true);
  }

  public boolean write(DataLog dataLog) {
    return LinkJVMJNI.CsvWriter_write(swigCPtr, this, DataLog.getCPtr(dataLog), dataLog);
  }

}
