/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni;

public class Object {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Object(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Object obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_Object(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Object(unsignedIntPoint2 centroid, unsignedIntRect2 boundingBox, double confidence, String data, long dataLength) {
    this(LinkJVMJNI.new_Object__SWIG_0(unsignedIntPoint2.getCPtr(centroid), centroid, unsignedIntRect2.getCPtr(boundingBox), boundingBox, confidence, data, dataLength), true);
  }

  public Object(unsignedIntPoint2 centroid, unsignedIntRect2 boundingBox, double confidence, String data) {
    this(LinkJVMJNI.new_Object__SWIG_1(unsignedIntPoint2.getCPtr(centroid), centroid, unsignedIntRect2.getCPtr(boundingBox), boundingBox, confidence, data), true);
  }

  public Object(unsignedIntPoint2 centroid, unsignedIntRect2 boundingBox, double confidence) {
    this(LinkJVMJNI.new_Object__SWIG_2(unsignedIntPoint2.getCPtr(centroid), centroid, unsignedIntRect2.getCPtr(boundingBox), boundingBox, confidence), true);
  }

  public Object(Object rhs) {
    this(LinkJVMJNI.new_Object__SWIG_3(Object.getCPtr(rhs), rhs), true);
  }

  public unsignedIntPoint2 centroid() {
    return new unsignedIntPoint2(LinkJVMJNI.Object_centroid(swigCPtr, this), false);
  }

  public unsignedIntRect2 boundingBox() {
    return new unsignedIntRect2(LinkJVMJNI.Object_boundingBox(swigCPtr, this), false);
  }

  public double confidence() {
    return LinkJVMJNI.Object_confidence(swigCPtr, this);
  }

  public String data() {
    return LinkJVMJNI.Object_data(swigCPtr, this);
  }

  public long dataLength() {
    return LinkJVMJNI.Object_dataLength(swigCPtr, this);
  }

}
