/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.create;

public class linkjvm_createJNI {
  public final static native long new_CreateScript__SWIG_0();
  public final static native long new_CreateScript__SWIG_1(long jarg1, CreateScript jarg1_);
  public final static native void CreateScript_append__SWIG_0(long jarg1, CreateScript jarg1_, short jarg2);
  public final static native void CreateScript_append__SWIG_1(long jarg1, CreateScript jarg1_, long jarg2, long jarg3);
  public final static native void CreateScript_append__SWIG_2(long jarg1, CreateScript jarg1_, long jarg2, CreateScript jarg2_);
  public final static native void CreateScript_remove__SWIG_0(long jarg1, CreateScript jarg1_, long jarg2, long jarg3);
  public final static native void CreateScript_remove__SWIG_1(long jarg1, CreateScript jarg1_, long jarg2);
  public final static native long CreateScript_data(long jarg1, CreateScript jarg1_);
  public final static native long CreateScript_size(long jarg1, CreateScript jarg1_);
  public final static native short CreateScript__byte(long jarg1, CreateScript jarg1_, long jarg2);
  public final static native void delete_CreateScript(long jarg1);
  public final static native void CreateState_timestamp_set(long jarg1, CreateState jarg1_, long jarg2);
  public final static native long CreateState_timestamp_get(long jarg1, CreateState jarg1_);
  public final static native void CreateState_distance_set(long jarg1, CreateState jarg1_, int jarg2);
  public final static native int CreateState_distance_get(long jarg1, CreateState jarg1_);
  public final static native void CreateState_angle_set(long jarg1, CreateState jarg1_, int jarg2);
  public final static native int CreateState_angle_get(long jarg1, CreateState jarg1_);
  public final static native void CreateState_radius_set(long jarg1, CreateState jarg1_, short jarg2);
  public final static native short CreateState_radius_get(long jarg1, CreateState jarg1_);
  public final static native void CreateState_rightVelocity_set(long jarg1, CreateState jarg1_, short jarg2);
  public final static native short CreateState_rightVelocity_get(long jarg1, CreateState jarg1_);
  public final static native void CreateState_leftVelocity_set(long jarg1, CreateState jarg1_, short jarg2);
  public final static native short CreateState_leftVelocity_get(long jarg1, CreateState jarg1_);
  public final static native long new_CreateState();
  public final static native void delete_CreateState(long jarg1);
  public final static native void delete_Create(long jarg1);
  public final static native boolean Create_connect(long jarg1, Create jarg1_);
  public final static native boolean Create_disconnect(long jarg1, Create jarg1_);
  public final static native boolean Create_isConnected(long jarg1, Create jarg1_);
  public final static native void Create_setPassiveMode(long jarg1, Create jarg1_);
  public final static native void Create_setSafeMode(long jarg1, Create jarg1_);
  public final static native void Create_setFullMode(long jarg1, Create jarg1_);
  public final static native void Create_setMode(long jarg1, Create jarg1_, int jarg2);
  public final static native int Create_mode(long jarg1, Create jarg1_);
  public final static native void Create_send(long jarg1, Create jarg1_, long jarg2, CreateScript jarg2_);
  public final static native boolean Create_write__SWIG_0(long jarg1, Create jarg1_, short jarg2);
  public final static native boolean Create_write__SWIG_1(long jarg1, Create jarg1_, long jarg2, long jarg3);
  public final static native void Create_flush(long jarg1, Create jarg1_);
  public final static native short Create_read__SWIG_0(long jarg1, Create jarg1_);
  public final static native int Create_read__SWIG_1(long jarg1, Create jarg1_, long jarg2, long jarg3);
  public final static native boolean Create_blockingRead__SWIG_0(long jarg1, Create jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native boolean Create_blockingRead__SWIG_1(long jarg1, Create jarg1_, long jarg2, long jarg3);
  public final static native void Create_setLeds(long jarg1, Create jarg1_, boolean jarg2, boolean jarg3, short jarg4, short jarg5);
  public final static native void Create_drive(long jarg1, Create jarg1_, short jarg2, short jarg3);
  public final static native void Create_driveDirect(long jarg1, Create jarg1_, short jarg2, short jarg3);
  public final static native void Create_driveStraight(long jarg1, Create jarg1_, short jarg2);
  public final static native void Create_stop(long jarg1, Create jarg1_);
  public final static native void Create_turn(long jarg1, Create jarg1_, short jarg2, int jarg3);
  public final static native void Create_move(long jarg1, Create jarg1_, short jarg2, int jarg3);
  public final static native void Create_spin(long jarg1, Create jarg1_, short jarg2);
  public final static native short Create_angularVelocity(long jarg1, Create jarg1_);
  public final static native void Create_spinClockwise(long jarg1, Create jarg1_, short jarg2);
  public final static native void Create_spinCounterClockwise(long jarg1, Create jarg1_, short jarg2);
  public final static native boolean Create_setBaudRate(long jarg1, Create jarg1_, short jarg2);
  public final static native void Create_setDistance(long jarg1, Create jarg1_, int jarg2);
  public final static native void Create_setAngle(long jarg1, Create jarg1_, int jarg2);
  public final static native long Create_playButton(long jarg1, Create jarg1_);
  public final static native long Create_advanceButton(long jarg1, Create jarg1_);
  public final static native long Create_wall(long jarg1, Create jarg1_);
  public final static native long Create_cliffLeft(long jarg1, Create jarg1_);
  public final static native long Create_cliffFrontLeft(long jarg1, Create jarg1_);
  public final static native long Create_cliffFrontRight(long jarg1, Create jarg1_);
  public final static native long Create_cliffRight(long jarg1, Create jarg1_);
  public final static native long Create_virtualWall(long jarg1, Create jarg1_);
  public final static native long Create_wallSignal(long jarg1, Create jarg1_);
  public final static native long Create_cliffLeftSignal(long jarg1, Create jarg1_);
  public final static native long Create_cliffFrontLeftSignal(long jarg1, Create jarg1_);
  public final static native long Create_cliffFrontRightSignal(long jarg1, Create jarg1_);
  public final static native long Create_cliffRightSignal(long jarg1, Create jarg1_);
  public final static native long Create_cargoBayAnalogSignal(long jarg1, Create jarg1_);
  public final static native long Create_cargoBayDigitalInputs(long jarg1, Create jarg1_);
  public final static native long Create_ir(long jarg1, Create jarg1_);
  public final static native long Create_chargingState(long jarg1, Create jarg1_);
  public final static native long Create_batteryTemperature(long jarg1, Create jarg1_);
  public final static native long Create_batteryCharge(long jarg1, Create jarg1_);
  public final static native long Create_batteryCapacity(long jarg1, Create jarg1_);
  public final static native long Create_angle(long jarg1, Create jarg1_);
  public final static native long Create_distance(long jarg1, Create jarg1_);
  public final static native long Create_bumpLeft(long jarg1, Create jarg1_);
  public final static native long Create_bumpRight(long jarg1, Create jarg1_);
  public final static native long Create_wheelDropLeft(long jarg1, Create jarg1_);
  public final static native long Create_wheelDropRight(long jarg1, Create jarg1_);
  public final static native long Create_wheelDropCaster(long jarg1, Create jarg1_);
  public final static native void Create_setRefreshRate(long jarg1, Create jarg1_, int jarg2);
  public final static native int Create_refreshRate(long jarg1, Create jarg1_);
  public final static native long Create_instance();
  public final static native long Create_state(long jarg1, Create jarg1_);
}
