/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.geom;

public class linkjvm_geomJNI {
  public final static native void point2_x_set(long jarg1, point2 jarg1_, int jarg2);
  public final static native int point2_x_get(long jarg1, point2 jarg1_);
  public final static native void point2_y_set(long jarg1, point2 jarg1_, int jarg2);
  public final static native int point2_y_get(long jarg1, point2 jarg1_);
  public final static native long new_point2();
  public final static native void delete_point2(long jarg1);
  public final static native void rectangle_ulx_set(long jarg1, rectangle jarg1_, int jarg2);
  public final static native int rectangle_ulx_get(long jarg1, rectangle jarg1_);
  public final static native void rectangle_uly_set(long jarg1, rectangle jarg1_, int jarg2);
  public final static native int rectangle_uly_get(long jarg1, rectangle jarg1_);
  public final static native void rectangle_width_set(long jarg1, rectangle jarg1_, int jarg2);
  public final static native int rectangle_width_get(long jarg1, rectangle jarg1_);
  public final static native void rectangle_height_set(long jarg1, rectangle jarg1_, int jarg2);
  public final static native int rectangle_height_get(long jarg1, rectangle jarg1_);
  public final static native long new_rectangle();
  public final static native void delete_rectangle(long jarg1);
  public final static native long new_unsignedIntPoint2(long jarg1, long jarg2);
  public final static native long unsignedIntPoint2_x(long jarg1, unsignedIntPoint2 jarg1_);
  public final static native long unsignedIntPoint2_y(long jarg1, unsignedIntPoint2 jarg1_);
  public final static native void unsignedIntPoint2_setX(long jarg1, unsignedIntPoint2 jarg1_, long jarg2);
  public final static native void unsignedIntPoint2_setY(long jarg1, unsignedIntPoint2 jarg1_, long jarg2);
  public final static native long unsignedIntPoint2_toCPoint2(long jarg1, unsignedIntPoint2 jarg1_);
  public final static native void delete_unsignedIntPoint2(long jarg1);
  public final static native long new_unsignedIntRect2(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long unsignedIntRect2_x(long jarg1, unsignedIntRect2 jarg1_);
  public final static native long unsignedIntRect2_y(long jarg1, unsignedIntRect2 jarg1_);
  public final static native long unsignedIntRect2_width(long jarg1, unsignedIntRect2 jarg1_);
  public final static native long unsignedIntRect2_height(long jarg1, unsignedIntRect2 jarg1_);
  public final static native long unsignedIntRect2_center(long jarg1, unsignedIntRect2 jarg1_);
  public final static native void unsignedIntRect2_setX(long jarg1, unsignedIntRect2 jarg1_, long jarg2);
  public final static native void unsignedIntRect2_setY(long jarg1, unsignedIntRect2 jarg1_, long jarg2);
  public final static native void unsignedIntRect2_setWidth(long jarg1, unsignedIntRect2 jarg1_, long jarg2);
  public final static native void unsignedIntRect2_setHeight(long jarg1, unsignedIntRect2 jarg1_, long jarg2);
  public final static native long unsignedIntRect2_area(long jarg1, unsignedIntRect2 jarg1_);
  public final static native long unsignedIntRect2_toCRectangle(long jarg1, unsignedIntRect2 jarg1_);
  public final static native void delete_unsignedIntRect2(long jarg1);
}
