/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class _1 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _1(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_1 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete__1(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBumpsAndWheelDrops(short value) {
    LinkJVMJNI._1_bumpsAndWheelDrops_set(swigCPtr, this, value);
  }

  public short getBumpsAndWheelDrops() {
    return LinkJVMJNI._1_bumpsAndWheelDrops_get(swigCPtr, this);
  }

  public void setWall(short value) {
    LinkJVMJNI._1_wall_set(swigCPtr, this, value);
  }

  public short getWall() {
    return LinkJVMJNI._1_wall_get(swigCPtr, this);
  }

  public void setCliffLeft(short value) {
    LinkJVMJNI._1_cliffLeft_set(swigCPtr, this, value);
  }

  public short getCliffLeft() {
    return LinkJVMJNI._1_cliffLeft_get(swigCPtr, this);
  }

  public void setCliffFrontLeft(short value) {
    LinkJVMJNI._1_cliffFrontLeft_set(swigCPtr, this, value);
  }

  public short getCliffFrontLeft() {
    return LinkJVMJNI._1_cliffFrontLeft_get(swigCPtr, this);
  }

  public void setCliffFrontRight(short value) {
    LinkJVMJNI._1_cliffFrontRight_set(swigCPtr, this, value);
  }

  public short getCliffFrontRight() {
    return LinkJVMJNI._1_cliffFrontRight_get(swigCPtr, this);
  }

  public void setCliffRight(short value) {
    LinkJVMJNI._1_cliffRight_set(swigCPtr, this, value);
  }

  public short getCliffRight() {
    return LinkJVMJNI._1_cliffRight_get(swigCPtr, this);
  }

  public void setVirtualWall(short value) {
    LinkJVMJNI._1_virtualWall_set(swigCPtr, this, value);
  }

  public short getVirtualWall() {
    return LinkJVMJNI._1_virtualWall_get(swigCPtr, this);
  }

  public void setCargoBayDigitalInputs(short value) {
    LinkJVMJNI._1_cargoBayDigitalInputs_set(swigCPtr, this, value);
  }

  public short getCargoBayDigitalInputs() {
    return LinkJVMJNI._1_cargoBayDigitalInputs_get(swigCPtr, this);
  }

  public void setLowSideDriverAndWheelOvercurrents(short value) {
    LinkJVMJNI._1_lowSideDriverAndWheelOvercurrents_set(swigCPtr, this, value);
  }

  public short getLowSideDriverAndWheelOvercurrents() {
    return LinkJVMJNI._1_lowSideDriverAndWheelOvercurrents_get(swigCPtr, this);
  }

  public _1() {
    this(LinkJVMJNI.new__1(), true);
  }

}
