/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class _2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete__2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIr(short value) {
    LinkJVMJNI._2_ir_set(swigCPtr, this, value);
  }

  public short getIr() {
    return LinkJVMJNI._2_ir_get(swigCPtr, this);
  }

  public void setButtons(short value) {
    LinkJVMJNI._2_buttons_set(swigCPtr, this, value);
  }

  public short getButtons() {
    return LinkJVMJNI._2_buttons_get(swigCPtr, this);
  }

  public void setDistance(SWIGTYPE_p_unsigned_char value) {
    LinkJVMJNI._2_distance_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getDistance() {
    long cPtr = LinkJVMJNI._2_distance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAngle(SWIGTYPE_p_unsigned_char value) {
    LinkJVMJNI._2_angle_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getAngle() {
    long cPtr = LinkJVMJNI._2_angle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public _2() {
    this(LinkJVMJNI.new__2(), true);
  }

}
