/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class _3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete__3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setChargingState(short value) {
    LinkJVMJNI._3_chargingState_set(swigCPtr, this, value);
  }

  public short getChargingState() {
    return LinkJVMJNI._3_chargingState_get(swigCPtr, this);
  }

  public void setVoltage(SWIGTYPE_p_unsigned_char value) {
    LinkJVMJNI._3_voltage_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getVoltage() {
    long cPtr = LinkJVMJNI._3_voltage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setCurrent(String value) {
    LinkJVMJNI._3_current_set(swigCPtr, this, value);
  }

  public String getCurrent() {
    return LinkJVMJNI._3_current_get(swigCPtr, this);
  }

  public void setBatteryTemperature(char value) {
    LinkJVMJNI._3_batteryTemperature_set(swigCPtr, this, value);
  }

  public char getBatteryTemperature() {
    return LinkJVMJNI._3_batteryTemperature_get(swigCPtr, this);
  }

  public void setBatteryCharge(SWIGTYPE_p_unsigned_char value) {
    LinkJVMJNI._3_batteryCharge_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getBatteryCharge() {
    long cPtr = LinkJVMJNI._3_batteryCharge_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setBatteryCapacity(SWIGTYPE_p_unsigned_char value) {
    LinkJVMJNI._3_batteryCapacity_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getBatteryCapacity() {
    long cPtr = LinkJVMJNI._3_batteryCapacity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public _3() {
    this(LinkJVMJNI.new__3(), true);
  }

}
