/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class _5 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _5(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_5 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete__5(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(short value) {
    LinkJVMJNI._5_mode_set(swigCPtr, this, value);
  }

  public short getMode() {
    return LinkJVMJNI._5_mode_get(swigCPtr, this);
  }

  public void setSongNumber(short value) {
    LinkJVMJNI._5_songNumber_set(swigCPtr, this, value);
  }

  public short getSongNumber() {
    return LinkJVMJNI._5_songNumber_get(swigCPtr, this);
  }

  public void setSongPlaying(short value) {
    LinkJVMJNI._5_songPlaying_set(swigCPtr, this, value);
  }

  public short getSongPlaying() {
    return LinkJVMJNI._5_songPlaying_get(swigCPtr, this);
  }

  public void setNumberOfStreamPackets(short value) {
    LinkJVMJNI._5_numberOfStreamPackets_set(swigCPtr, this, value);
  }

  public short getNumberOfStreamPackets() {
    return LinkJVMJNI._5_numberOfStreamPackets_get(swigCPtr, this);
  }

  public void setVelocity(String value) {
    LinkJVMJNI._5_velocity_set(swigCPtr, this, value);
  }

  public String getVelocity() {
    return LinkJVMJNI._5_velocity_get(swigCPtr, this);
  }

  public void setRadius(String value) {
    LinkJVMJNI._5_radius_set(swigCPtr, this, value);
  }

  public String getRadius() {
    return LinkJVMJNI._5_radius_get(swigCPtr, this);
  }

  public void setRightVelocity(String value) {
    LinkJVMJNI._5_rightVelocity_set(swigCPtr, this, value);
  }

  public String getRightVelocity() {
    return LinkJVMJNI._5_rightVelocity_get(swigCPtr, this);
  }

  public void setLeftVelocity(String value) {
    LinkJVMJNI._5_leftVelocity_set(swigCPtr, this, value);
  }

  public String getLeftVelocity() {
    return LinkJVMJNI._5_leftVelocity_get(swigCPtr, this);
  }

  public _5() {
    this(LinkJVMJNI.new__5(), true);
  }

}
