/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class AbstractButton extends BoolSensor {
  private long swigCPtr;

  protected AbstractButton(long cPtr, boolean cMemoryOwn) {
    super(LinkJVMJNI.AbstractButton_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AbstractButton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_AbstractButton(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setPressed(boolean pressed) {
    LinkJVMJNI.AbstractButton_setPressed(swigCPtr, this, pressed);
  }

  public boolean isPressed() {
    return LinkJVMJNI.AbstractButton_isPressed(swigCPtr, this);
  }

  public boolean isNotPressed() {
    return LinkJVMJNI.AbstractButton_isNotPressed(swigCPtr, this);
  }

  public boolean isClicked() {
    return LinkJVMJNI.AbstractButton_isClicked(swigCPtr, this);
  }

  public void waitUntilReleased() {
    LinkJVMJNI.AbstractButton_waitUntilReleased(swigCPtr, this);
  }

  public void waitUntilPressed() {
    LinkJVMJNI.AbstractButton_waitUntilPressed(swigCPtr, this);
  }

  public void waitUntilClicked() {
    LinkJVMJNI.AbstractButton_waitUntilClicked(swigCPtr, this);
  }

}
