/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class AccelX {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AccelX(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AccelX obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_AccelX(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public short value() {
    return LinkJVMJNI.AccelX_value(swigCPtr, this);
  }

  public AccelX() {
    this(LinkJVMJNI.new_AccelX(), true);
  }

}
