/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class Analog8 extends Analog {
  private long swigCPtr;

  protected Analog8(long cPtr, boolean cMemoryOwn) {
    super(LinkJVMJNI.Analog8_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Analog8 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_Analog8(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Analog8(short port) {
    this(LinkJVMJNI.new_Analog8(port), true);
  }

  public int value() {
    return LinkJVMJNI.Analog8_value(swigCPtr, this);
  }

}
