/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class And extends Base {
  private long swigCPtr;

  protected And(long cPtr, boolean cMemoryOwn) {
    super(LinkJVMJNI.And_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(And obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_And(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public And(SWIGTYPE_p_SensorT_bool_t a, SWIGTYPE_p_SensorT_bool_t b, boolean owns) {
    this(LinkJVMJNI.new_And__SWIG_0(SWIGTYPE_p_SensorT_bool_t.getCPtr(a), SWIGTYPE_p_SensorT_bool_t.getCPtr(b), owns), true);
  }

  public And(SWIGTYPE_p_SensorT_bool_t a, SWIGTYPE_p_SensorT_bool_t b) {
    this(LinkJVMJNI.new_And__SWIG_1(SWIGTYPE_p_SensorT_bool_t.getCPtr(a), SWIGTYPE_p_SensorT_bool_t.getCPtr(b)), true);
  }

  public boolean value() {
    return LinkJVMJNI.And_value(swigCPtr, this);
  }

}
