/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class Base {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Base(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Base obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_Base(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Base(SWIGTYPE_p_SensorT_bool_t a, SWIGTYPE_p_SensorT_bool_t b, boolean owns) {
    this(LinkJVMJNI.new_Base__SWIG_0(SWIGTYPE_p_SensorT_bool_t.getCPtr(a), SWIGTYPE_p_SensorT_bool_t.getCPtr(b), owns), true);
  }

  public Base(SWIGTYPE_p_SensorT_bool_t a, SWIGTYPE_p_SensorT_bool_t b) {
    this(LinkJVMJNI.new_Base__SWIG_1(SWIGTYPE_p_SensorT_bool_t.getCPtr(a), SWIGTYPE_p_SensorT_bool_t.getCPtr(b)), true);
  }

  public SWIGTYPE_p_SensorT_bool_t a() {
    long cPtr = LinkJVMJNI.Base_a(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SensorT_bool_t(cPtr, false);
  }

  public SWIGTYPE_p_SensorT_bool_t b() {
    long cPtr = LinkJVMJNI.Base_b(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SensorT_bool_t(cPtr, false);
  }

  public boolean owns() {
    return LinkJVMJNI.Base_owns(swigCPtr, this);
  }

}
