/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class DataLogWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataLogWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataLogWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_DataLogWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean write(DataLog dataLog) {
    return LinkJVMJNI.DataLogWriter_write(swigCPtr, this, DataLog.getCPtr(dataLog), dataLog);
  }

}
