/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class ExtraButtons {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExtraButtons(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtraButtons obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_ExtraButtons(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void show() {
    LinkJVMJNI.ExtraButtons_show();
  }

  public static void hide() {
    LinkJVMJNI.ExtraButtons_hide();
  }

  public static void setShown(boolean shown) {
    LinkJVMJNI.ExtraButtons_setShown(shown);
  }

  public static boolean isShown() {
    return LinkJVMJNI.ExtraButtons_isShown();
  }

  public ExtraButtons() {
    this(LinkJVMJNI.new_ExtraButtons(), true);
  }

}
