/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public final class Id {
  public final static Id A = new Id("A");
  public final static Id B = new Id("B");
  public final static Id C = new Id("C");
  public final static Id X = new Id("X");
  public final static Id Y = new Id("Y");
  public final static Id Z = new Id("Z");
  public final static Id Side = new Id("Side");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Id swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Id.class + " with value " + swigValue);
  }

  private Id(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Id(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Id(String swigName, Id swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Id[] swigValues = { A, B, C, X, Y, Z, Side };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

