/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public interface LinkJVMConstants {
  public final static String CAMERA_GROUP = LinkJVMJNI.CAMERA_GROUP_get();
  public final static String CAMERA_NUM_CHANNELS_KEY = LinkJVMJNI.CAMERA_NUM_CHANNELS_KEY_get();
  public final static String CAMERA_CHANNEL_GROUP_PREFIX = LinkJVMJNI.CAMERA_CHANNEL_GROUP_PREFIX_get();
  public final static String CAMERA_CHANNEL_TYPE_KEY = LinkJVMJNI.CAMERA_CHANNEL_TYPE_KEY_get();
  public final static String CAMERA_CHANNEL_TYPE_HSV_KEY = LinkJVMJNI.CAMERA_CHANNEL_TYPE_HSV_KEY_get();
  public final static String CAMERA_CHANNEL_TYPE_QR_KEY = LinkJVMJNI.CAMERA_CHANNEL_TYPE_QR_KEY_get();
  public final static double PI = LinkJVMJNI.PI_get();
}
