/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class LinkJVM implements LinkJVMConstants {
  public static void setA(IdButton value) {
    LinkJVMJNI.A_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getA() {
    long cPtr = LinkJVMJNI.A_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setB(IdButton value) {
    LinkJVMJNI.B_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getB() {
    long cPtr = LinkJVMJNI.B_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setC(IdButton value) {
    LinkJVMJNI.C_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getC() {
    long cPtr = LinkJVMJNI.C_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setX(IdButton value) {
    LinkJVMJNI.X_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getX() {
    long cPtr = LinkJVMJNI.X_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setY(IdButton value) {
    LinkJVMJNI.Y_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getY() {
    long cPtr = LinkJVMJNI.Y_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setZ(IdButton value) {
    LinkJVMJNI.Z_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getZ() {
    long cPtr = LinkJVMJNI.Z_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static void setSide(IdButton value) {
    LinkJVMJNI.Side_set(IdButton.getCPtr(value), value);
  }

  public static IdButton getSide() {
    long cPtr = LinkJVMJNI.Side_get();
    return (cPtr == 0) ? null : new IdButton(cPtr, false);
  }

  public static SWIGTYPE_p_p_IdButton getAll() {
    long cPtr = LinkJVMJNI.all_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_IdButton(cPtr, false);
  }

  public static Device cDevice() {
    long cPtr = LinkJVMJNI.cDevice();
    return (cPtr == 0) ? null : new Device(cPtr, false);
  }

}
