/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class Not {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Not(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Not obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_Not(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Not(SWIGTYPE_p_SensorT_bool_t input, boolean owns) {
    this(LinkJVMJNI.new_Not__SWIG_0(SWIGTYPE_p_SensorT_bool_t.getCPtr(input), owns), true);
  }

  public Not(SWIGTYPE_p_SensorT_bool_t input) {
    this(LinkJVMJNI.new_Not__SWIG_1(SWIGTYPE_p_SensorT_bool_t.getCPtr(input)), true);
  }

  public boolean value() {
    return LinkJVMJNI.Not_value(swigCPtr, this);
  }

  public SWIGTYPE_p_SensorT_bool_t input() {
    long cPtr = LinkJVMJNI.Not_input(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SensorT_bool_t(cPtr, false);
  }

  public boolean owns() {
    return LinkJVMJNI.Not_owns(swigCPtr, this);
  }

}
