/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.libkovan;

public class Servo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Servo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Servo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_Servo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Servo(SWIGTYPE_p_port_t port) {
    this(LinkJVMJNI.new_Servo(SWIGTYPE_p_port_t.getCPtr(port)), true);
  }

  public void setPosition(long position) {
    LinkJVMJNI.Servo_setPosition(swigCPtr, this, position);
  }

  public long position() {
    return LinkJVMJNI.Servo_position(swigCPtr, this);
  }

  public void disable() {
    LinkJVMJNI.Servo_disable(swigCPtr, this);
  }

  public void enable() {
    LinkJVMJNI.Servo_enable(swigCPtr, this);
  }

  public void setEnabled(boolean enabled) {
    LinkJVMJNI.Servo_setEnabled(swigCPtr, this, enabled);
  }

  public boolean isEnabled() {
    return LinkJVMJNI.Servo_isEnabled(swigCPtr, this);
  }

}
