/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni.camera;

public class ObjectVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ObjectVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_cameraJNI.delete_ObjectVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ObjectVector() {
    this(linkjvm_cameraJNI.new_ObjectVector__SWIG_0(), true);
  }

  public ObjectVector(long n) {
    this(linkjvm_cameraJNI.new_ObjectVector__SWIG_1(n), true);
  }

  public long size() {
    return linkjvm_cameraJNI.ObjectVector_size(swigCPtr, this);
  }

  public long capacity() {
    return linkjvm_cameraJNI.ObjectVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    linkjvm_cameraJNI.ObjectVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return linkjvm_cameraJNI.ObjectVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    linkjvm_cameraJNI.ObjectVector_clear(swigCPtr, this);
  }

  public void add(Object x) {
    linkjvm_cameraJNI.ObjectVector_add(swigCPtr, this, Object.getCPtr(x), x);
  }

  public Object get(int i) {
    return new Object(linkjvm_cameraJNI.ObjectVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Object val) {
    linkjvm_cameraJNI.ObjectVector_set(swigCPtr, this, i, Object.getCPtr(val), val);
  }

}
