/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.geom;

public class unsignedIntPoint2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected unsignedIntPoint2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(unsignedIntPoint2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_geomJNI.delete_unsignedIntPoint2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public unsignedIntPoint2(long x, long y) {
    this(linkjvm_geomJNI.new_unsignedIntPoint2(x, y), true);
  }

  public long x() {
    return linkjvm_geomJNI.unsignedIntPoint2_x(swigCPtr, this);
  }

  public long y() {
    return linkjvm_geomJNI.unsignedIntPoint2_y(swigCPtr, this);
  }

  public void setX(long x) {
    linkjvm_geomJNI.unsignedIntPoint2_setX(swigCPtr, this, x);
  }

  public void setY(long y) {
    linkjvm_geomJNI.unsignedIntPoint2_setY(swigCPtr, this, y);
  }

  public point2 toCPoint2() {
    return new point2(linkjvm_geomJNI.unsignedIntPoint2_toCPoint2(swigCPtr, this), true);
  }

}
