/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.vision;

public final class DepthResolution {
  public final static DepthResolution DEPTH_INVALID_RESOLUTION = new DepthResolution("DEPTH_INVALID_RESOLUTION");
  public final static DepthResolution DEPTH_RESOLUTION_320_240 = new DepthResolution("DEPTH_RESOLUTION_320_240");
  public final static DepthResolution DEPTH_RESOLUTION_640_480 = new DepthResolution("DEPTH_RESOLUTION_640_480");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DepthResolution swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DepthResolution.class + " with value " + swigValue);
  }

  private DepthResolution(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DepthResolution(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DepthResolution(String swigName, DepthResolution swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DepthResolution[] swigValues = { DEPTH_INVALID_RESOLUTION, DEPTH_RESOLUTION_320_240, DEPTH_RESOLUTION_640_480 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

