/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.vision;

public class InputProvider {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected InputProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_visionJNI.delete_InputProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean open(int number) {
    return linkjvm_visionJNI.InputProvider_open(swigCPtr, this, number);
  }

  public boolean isOpen() {
    return linkjvm_visionJNI.InputProvider_isOpen(swigCPtr, this);
  }

  public void setWidth(long width) {
    linkjvm_visionJNI.InputProvider_setWidth(swigCPtr, this, width);
  }

  public void setHeight(long height) {
    linkjvm_visionJNI.InputProvider_setHeight(swigCPtr, this, height);
  }

  public boolean next(SWIGTYPE_p_cv__Mat image) {
    return linkjvm_visionJNI.InputProvider_next(swigCPtr, this, SWIGTYPE_p_cv__Mat.getCPtr(image));
  }

  public boolean close() {
    return linkjvm_visionJNI.InputProvider_close(swigCPtr, this);
  }

}
