/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.vision;

public class IntPoint3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntPoint3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntPoint3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_visionJNI.delete_IntPoint3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntPoint3(int x, int y, int z) {
    this(linkjvm_visionJNI.new_IntPoint3(x, y, z), true);
  }

  public int x() {
    return linkjvm_visionJNI.IntPoint3_x(swigCPtr, this);
  }

  public int y() {
    return linkjvm_visionJNI.IntPoint3_y(swigCPtr, this);
  }

  public int z() {
    return linkjvm_visionJNI.IntPoint3_z(swigCPtr, this);
  }

  public void setX(int x) {
    linkjvm_visionJNI.IntPoint3_setX(swigCPtr, this, x);
  }

  public void setY(int y) {
    linkjvm_visionJNI.IntPoint3_setY(swigCPtr, this, y);
  }

  public void setZ(int z) {
    linkjvm_visionJNI.IntPoint3_setZ(swigCPtr, this, z);
  }

  public SWIGTYPE_p_point3 toCPoint3() {
    return new SWIGTYPE_p_point3(linkjvm_visionJNI.IntPoint3_toCPoint3(swigCPtr, this), true);
  }

}
