/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.vision;

public class IntRectangle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntRectangle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntRectangle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_visionJNI.delete_IntRectangle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntRectangle(long x, long y, long width, long height) {
    this(linkjvm_visionJNI.new_IntRectangle(x, y, width, height), true);
  }

  public long x() {
    return linkjvm_visionJNI.IntRectangle_x(swigCPtr, this);
  }

  public long y() {
    return linkjvm_visionJNI.IntRectangle_y(swigCPtr, this);
  }

  public long width() {
    return linkjvm_visionJNI.IntRectangle_width(swigCPtr, this);
  }

  public long height() {
    return linkjvm_visionJNI.IntRectangle_height(swigCPtr, this);
  }

  public IntPoint2 center() {
    return new IntPoint2(linkjvm_visionJNI.IntRectangle_center(swigCPtr, this), true);
  }

  public void setX(long x) {
    linkjvm_visionJNI.IntRectangle_setX(swigCPtr, this, x);
  }

  public void setY(long y) {
    linkjvm_visionJNI.IntRectangle_setY(swigCPtr, this, y);
  }

  public void setWidth(long width) {
    linkjvm_visionJNI.IntRectangle_setWidth(swigCPtr, this, width);
  }

  public void setHeight(long height) {
    linkjvm_visionJNI.IntRectangle_setHeight(swigCPtr, this, height);
  }

  public long area() {
    return linkjvm_visionJNI.IntRectangle_area(swigCPtr, this);
  }

  public rectangle toCRectangle() {
    return new rectangle(linkjvm_visionJNI.IntRectangle_toCRectangle(swigCPtr, this), true);
  }

}
