/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.vision;

public class linkjvm_vision implements linkjvm_visionConstants {
  public static Device cDevice() {
    long cPtr = linkjvm_visionJNI.cDevice();
    return (cPtr == 0) ? null : new Device(cPtr, false);
  }

}
