/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.vision;

public class Object {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Object(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Object obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_visionJNI.delete_Object(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Object(IntPoint2 centroid, IntRectangle boundingBox, double confidence, String data, long dataLength) {
    this(linkjvm_visionJNI.new_Object__SWIG_0(IntPoint2.getCPtr(centroid), centroid, IntRectangle.getCPtr(boundingBox), boundingBox, confidence, data, dataLength), true);
  }

  public Object(IntPoint2 centroid, IntRectangle boundingBox, double confidence, String data) {
    this(linkjvm_visionJNI.new_Object__SWIG_1(IntPoint2.getCPtr(centroid), centroid, IntRectangle.getCPtr(boundingBox), boundingBox, confidence, data), true);
  }

  public Object(IntPoint2 centroid, IntRectangle boundingBox, double confidence) {
    this(linkjvm_visionJNI.new_Object__SWIG_2(IntPoint2.getCPtr(centroid), centroid, IntRectangle.getCPtr(boundingBox), boundingBox, confidence), true);
  }

  public Object(Object rhs) {
    this(linkjvm_visionJNI.new_Object__SWIG_3(Object.getCPtr(rhs), rhs), true);
  }

  public IntPoint2 centroid() {
    return new IntPoint2(linkjvm_visionJNI.Object_centroid(swigCPtr, this), false);
  }

  public IntRectangle boundingBox() {
    return new IntRectangle(linkjvm_visionJNI.Object_boundingBox(swigCPtr, this), false);
  }

  public double confidence() {
    return linkjvm_visionJNI.Object_confidence(swigCPtr, this);
  }

  public String data() {
    return linkjvm_visionJNI.Object_data(swigCPtr, this);
  }

  public long dataLength() {
    return linkjvm_visionJNI.Object_dataLength(swigCPtr, this);
  }

}
