/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.create;

public class CreateState {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CreateState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CreateState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_createJNI.delete_CreateState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimestamp(SWIGTYPE_p_timeval value) {
    linkjvm_createJNI.CreateState_timestamp_set(swigCPtr, this, SWIGTYPE_p_timeval.getCPtr(value));
  }

  public SWIGTYPE_p_timeval getTimestamp() {
    return new SWIGTYPE_p_timeval(linkjvm_createJNI.CreateState_timestamp_get(swigCPtr, this), true);
  }

  public void setDistance(int value) {
    linkjvm_createJNI.CreateState_distance_set(swigCPtr, this, value);
  }

  public int getDistance() {
    return linkjvm_createJNI.CreateState_distance_get(swigCPtr, this);
  }

  public void setAngle(int value) {
    linkjvm_createJNI.CreateState_angle_set(swigCPtr, this, value);
  }

  public int getAngle() {
    return linkjvm_createJNI.CreateState_angle_get(swigCPtr, this);
  }

  public void setRadius(short value) {
    linkjvm_createJNI.CreateState_radius_set(swigCPtr, this, value);
  }

  public short getRadius() {
    return linkjvm_createJNI.CreateState_radius_get(swigCPtr, this);
  }

  public void setRightVelocity(short value) {
    linkjvm_createJNI.CreateState_rightVelocity_set(swigCPtr, this, value);
  }

  public short getRightVelocity() {
    return linkjvm_createJNI.CreateState_rightVelocity_get(swigCPtr, this);
  }

  public void setLeftVelocity(short value) {
    linkjvm_createJNI.CreateState_leftVelocity_set(swigCPtr, this, value);
  }

  public short getLeftVelocity() {
    return linkjvm_createJNI.CreateState_leftVelocity_get(swigCPtr, this);
  }

  public CreateState() {
    this(linkjvm_createJNI.new_CreateState(), true);
  }

}
