/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni.sensors;

public class linkjvm_sensorJNI {
  public final static native void delete_IntSensor(long jarg1);
  public final static native int IntSensor_value(long jarg1, IntSensor jarg1_);
  public final static native void delete_UnsignedShortSensor(long jarg1);
  public final static native int UnsignedShortSensor_value(long jarg1, UnsignedShortSensor jarg1_);
  public final static native void delete_ShortSensor(long jarg1);
  public final static native short ShortSensor_value(long jarg1, ShortSensor jarg1_);
  public final static native void delete_BoolSensor(long jarg1);
  public final static native boolean BoolSensor_value(long jarg1, BoolSensor jarg1_);
  public final static native void delete_UnsignedCharSensor(long jarg1);
  public final static native short UnsignedCharSensor_value(long jarg1, UnsignedCharSensor jarg1_);
  public final static native void delete_CharSensor(long jarg1);
  public final static native char CharSensor_value(long jarg1, CharSensor jarg1_);
}
