/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.motors;
import linkjvm.low.sensors.IntSensor;
public class BackEMF extends IntSensor {
  private long swigCPtr;

  protected BackEMF(long cPtr, boolean cMemoryOwn) {
    super(linkjvm_motorJNI.BackEMF_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BackEMF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_motorJNI.delete_BackEMF(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BackEMF(short port) {
    this(linkjvm_motorJNI.new_BackEMF(port), true);
  }

  public int value() {
    return linkjvm_motorJNI.BackEMF_value(swigCPtr, this);
  }

  public short port() {
    return linkjvm_motorJNI.BackEMF_port(swigCPtr, this);
  }

}
