/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.accel;

public class Acceleration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Acceleration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Acceleration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_accelJNI.delete_Acceleration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static short x() {
    return linkjvm_accelJNI.Acceleration_x();
  }

  public static short y() {
    return linkjvm_accelJNI.Acceleration_y();
  }

  public static short z() {
    return linkjvm_accelJNI.Acceleration_z();
  }

  public static boolean calibrate() {
    return linkjvm_accelJNI.Acceleration_calibrate();
  }

  public Acceleration() {
    this(linkjvm_accelJNI.new_Acceleration(), true);
  }

}
