/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.accel;

public class linkjvm_accelJNI {
  public final static native short Acceleration_x();
  public final static native short Acceleration_y();
  public final static native short Acceleration_z();
  public final static native boolean Acceleration_calibrate();
  public final static native long new_Acceleration();
  public final static native void delete_Acceleration(long jarg1);
  public final static native short AccelX_value(long jarg1, AccelX jarg1_);
  public final static native long new_AccelX();
  public final static native void delete_AccelX(long jarg1);
  public final static native short AccelY_value(long jarg1, AccelY jarg1_);
  public final static native long new_AccelY();
  public final static native void delete_AccelY(long jarg1);
  public final static native short AccelZ_value(long jarg1, AccelZ jarg1_);
  public final static native long new_AccelZ();
  public final static native void delete_AccelZ(long jarg1);
  public final static native long AccelX_SWIGUpcast(long jarg1);
  public final static native long AccelY_SWIGUpcast(long jarg1);
  public final static native long AccelZ_SWIGUpcast(long jarg1);
}
