/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni.create;

public class CreateScript {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CreateScript(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CreateScript obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_createJNI.delete_CreateScript(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CreateScript() {
    this(linkjvm_createJNI.new_CreateScript__SWIG_0(), true);
  }

  public CreateScript(CreateScript rhs) {
    this(linkjvm_createJNI.new_CreateScript__SWIG_1(CreateScript.getCPtr(rhs), rhs), true);
  }

  public void append(short arg0) {
    linkjvm_createJNI.CreateScript_append__SWIG_0(swigCPtr, this, arg0);
  }

  public void append(SWIGTYPE_p_unsigned_char data, long size) {
    linkjvm_createJNI.CreateScript_append__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(data), size);
  }

  public void append(CreateScript script) {
    linkjvm_createJNI.CreateScript_append__SWIG_2(swigCPtr, this, CreateScript.getCPtr(script), script);
  }

  public void remove(long i, long len) {
    linkjvm_createJNI.CreateScript_remove__SWIG_0(swigCPtr, this, i, len);
  }

  public void remove(long i) {
    linkjvm_createJNI.CreateScript_remove__SWIG_1(swigCPtr, this, i);
  }

  public SWIGTYPE_p_unsigned_char data() {
    long cPtr = linkjvm_createJNI.CreateScript_data(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public long size() {
    return linkjvm_createJNI.CreateScript_size(swigCPtr, this);
  }

  public short _byte(long i) {
    return linkjvm_createJNI.CreateScript__byte(swigCPtr, this, i);
  }

}
