/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.linkjvm.jni.geom;

public class unsignedIntRect2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected unsignedIntRect2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(unsignedIntRect2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_geomJNI.delete_unsignedIntRect2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public unsignedIntRect2(long x, long y, long width, long height) {
    this(linkjvm_geomJNI.new_unsignedIntRect2(x, y, width, height), true);
  }

  public long x() {
    return linkjvm_geomJNI.unsignedIntRect2_x(swigCPtr, this);
  }

  public long y() {
    return linkjvm_geomJNI.unsignedIntRect2_y(swigCPtr, this);
  }

  public long width() {
    return linkjvm_geomJNI.unsignedIntRect2_width(swigCPtr, this);
  }

  public long height() {
    return linkjvm_geomJNI.unsignedIntRect2_height(swigCPtr, this);
  }

  public unsignedIntPoint2 center() {
    return new unsignedIntPoint2(linkjvm_geomJNI.unsignedIntRect2_center(swigCPtr, this), true);
  }

  public void setX(long x) {
    linkjvm_geomJNI.unsignedIntRect2_setX(swigCPtr, this, x);
  }

  public void setY(long y) {
    linkjvm_geomJNI.unsignedIntRect2_setY(swigCPtr, this, y);
  }

  public void setWidth(long width) {
    linkjvm_geomJNI.unsignedIntRect2_setWidth(swigCPtr, this, width);
  }

  public void setHeight(long height) {
    linkjvm_geomJNI.unsignedIntRect2_setHeight(swigCPtr, this, height);
  }

  public long area() {
    return linkjvm_geomJNI.unsignedIntRect2_area(swigCPtr, this);
  }

  public rectangle toCRectangle() {
    return new rectangle(linkjvm_geomJNI.unsignedIntRect2_toCRectangle(swigCPtr, this), true);
  }

}
