/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low;

public class Console {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Console(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Console obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_consoleJNI.delete_Console(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void clear() {
    linkjvm_consoleJNI.Console_clear();
  }

  public Console() {
    this(linkjvm_consoleJNI.new_Console(), true);
  }

}
