/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low;

public class linkjvm_digitalJNI {
  public final static native long new_Digital(short jarg1);
  public final static native void Digital_setValue(long jarg1, Digital jarg1_, boolean jarg2);
  public final static native boolean Digital_value(long jarg1, Digital jarg1_);
  public final static native void Digital_setOutput(long jarg1, Digital jarg1_, boolean jarg2);
  public final static native boolean Digital_isOutput(long jarg1, Digital jarg1_);
  public final static native void Digital_setPullup(long jarg1, Digital jarg1_, boolean jarg2);
  public final static native boolean Digital_pullup(long jarg1, Digital jarg1_);
  public final static native void delete_Digital(long jarg1);
  public final static native long Digital_SWIGUpcast(long jarg1);
}
