/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low;

public class linkjvm_batteryJNI {
  public final static native boolean Battery_isCharging();
  public final static native float Battery_powerLevel();
  public final static native long new_Battery();
  public final static native void delete_Battery(long jarg1);
}
