/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low;

public class linkjvm_irJNI {
  public final static native void Ir_read();
  public final static native void Ir_write();
  public final static native long new_Ir();
  public final static native void delete_Ir(long jarg1);
}
