/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


    #include "include/kovan/sensor.hpp"
    #include "include/kovan/button_ids.hpp"
    #include "include/kovan/button.hpp"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1waitUntilClicked(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  ((AbstractButton const *)arg1)->waitUntilClicked();
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_delete_1AbstractButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(AbstractButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1setPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->setPressed(arg2);
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1isPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (bool)((AbstractButton const *)arg1)->isPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1isNotPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (bool)((AbstractButton const *)arg1)->isNotPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1isClicked(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (bool)((AbstractButton const *)arg1)->isClicked();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1waitUntilReleased(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  ((AbstractButton const *)arg1)->waitUntilReleased();
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1waitUntilPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  ((AbstractButton const *)arg1)->waitUntilPressed();
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_delete_1AbstractTextButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  AbstractTextButton *arg1 = (AbstractTextButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(AbstractTextButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractTextButton_1setText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  AbstractTextButton *arg1 = (AbstractTextButton *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractTextButton **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->setText((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractTextButton_1text(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  AbstractTextButton *arg1 = (AbstractTextButton *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractTextButton **)&jarg1; 
  result = (char *)((AbstractTextButton const *)arg1)->text();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractTextButton_1isTextDirty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractTextButton *arg1 = (AbstractTextButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractTextButton **)&jarg1; 
  result = (bool)((AbstractTextButton const *)arg1)->isTextDirty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractTextButton_1resetText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  AbstractTextButton *arg1 = (AbstractTextButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractTextButton **)&jarg1; 
  (arg1)->resetText();
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_new_1IdButton(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  Button::Type::Id *arg1 = 0 ;
  char *arg2 = (char *) 0 ;
  Button::Type::Id temp1 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  temp1 = (Button::Type::Id)jarg1; 
  arg1 = &temp1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (IdButton *)new IdButton((Button::Type::Id const &)*arg1,(char const *)arg2);
  *(IdButton **)&jresult = result; 
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_delete_1IdButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(IdButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1setText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  IdButton *arg1 = (IdButton *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->setText((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1text(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  IdButton *arg1 = (IdButton *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  result = (char *)((IdButton const *)arg1)->text();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1isTextDirty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  IdButton *arg1 = (IdButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  result = (bool)((IdButton const *)arg1)->isTextDirty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1setPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  IdButton *arg1 = (IdButton *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->setPressed(arg2);
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1value(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  IdButton *arg1 = (IdButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  result = (bool)((IdButton const *)arg1)->value();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1resetText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  (arg1)->resetText();
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_ExtraButtons_1show(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ExtraButtons::show();
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_ExtraButtons_1hide(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ExtraButtons::hide();
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_ExtraButtons_1setShown(JNIEnv *jenv, jclass jcls, jboolean jarg1) {
  bool *arg1 = 0 ;
  bool temp1 ;
  
  (void)jenv;
  (void)jcls;
  temp1 = jarg1 ? true : false; 
  arg1 = &temp1; 
  ExtraButtons::setShown((bool const &)*arg1);
}


SWIGEXPORT jboolean JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_ExtraButtons_1isShown(JNIEnv *jenv, jclass jcls) {
  jboolean jresult = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  result = (bool)ExtraButtons::isShown();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_new_1ExtraButtons(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ExtraButtons *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ExtraButtons *)new ExtraButtons();
  *(ExtraButtons **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_delete_1ExtraButtons(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ExtraButtons *arg1 = (ExtraButtons *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ExtraButtons **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_A_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::A = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_A_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::A;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_B_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::B = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_B_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::B;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_C_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::C = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_C_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::C;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_X_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::X = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_X_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::X;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_Y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::Y = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_Y_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::Y;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_Z_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::Z = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_Z_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::Z;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_Side_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  IdButton *arg1 = (IdButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(IdButton **)&jarg1; 
  Button::Side = *arg1;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_Side_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton *)&Button::Side;
  *(IdButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_all_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  IdButton **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (IdButton **)(IdButton **)Button::all;
  *(IdButton ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractButton_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(Sensor< bool > **)&baseptr = *(AbstractButton **)&jarg1;
    return baseptr;
}

SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_AbstractTextButton_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(AbstractButton **)&baseptr = *(AbstractTextButton **)&jarg1;
    return baseptr;
}

SWIGEXPORT jlong JNICALL Java_linkjvm_low_buttons_linkjvm_1buttonsJNI_IdButton_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(AbstractTextButton **)&baseptr = *(IdButton **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

