/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "include/kovan/kovan.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1connect(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)drone_connect();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1disconnect(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  drone_disconnect();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1calibrate(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  drone_calibrate();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1version(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_drone_version();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1takeoff(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  drone_takeoff();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1land(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  drone_land();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1battery(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_drone_battery();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1clear_1position(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  drone_clear_position();
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1x(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_x();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1y(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_y();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1z(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_z();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1x_1velocity(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_x_velocity();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1y_1velocity(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_y_velocity();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1z_1velocity(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_z_velocity();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1pitch(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_pitch();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1roll(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_roll();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1altitude(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_altitude();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1yaw(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)get_drone_yaw();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1camera_1open(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  enum drone_camera arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum drone_camera)jarg1; 
  result = (int)drone_camera_open(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1drone_1mac_1address(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)set_drone_mac_address((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1pair(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)drone_pair();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1drone_1ssid(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)set_drone_ssid((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1move(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  drone_move(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_drone_1hover(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  drone_hover();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1drone_1emergency_1stop_1enabled(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_drone_emergency_stop_enabled(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1drone_1emergency_1stop_1enabled(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_drone_emergency_stop_enabled();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_beep(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  beep();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1motor_1position_1counter(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_motor_position_counter(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_clear_1motor_1position_1counter(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  clear_motor_position_counter(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_move_1at_1velocity(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)move_at_velocity(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_mav(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)mav(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_move_1to_1position(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)move_to_position(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_mtp(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)mtp(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_move_1relative_1position(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)move_relative_position(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_mrp(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)mrp(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1pid_1gains(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jshort jarg7) {
  int arg1 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  short arg7 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (short)jarg7; 
  set_pid_gains(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1pid_1gains(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7) {
  int arg1 ;
  short *arg2 = (short *) 0 ;
  short *arg3 = (short *) 0 ;
  short *arg4 = (short *) 0 ;
  short *arg5 = (short *) 0 ;
  short *arg6 = (short *) 0 ;
  short *arg7 = (short *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(short **)&jarg2; 
  arg3 = *(short **)&jarg3; 
  arg4 = *(short **)&jarg4; 
  arg5 = *(short **)&jarg5; 
  arg6 = *(short **)&jarg6; 
  arg7 = *(short **)&jarg7; 
  get_pid_gains(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_freeze(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)freeze(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1motor_1done(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_motor_done(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_block_1motor_1done(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  block_motor_done(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_bmd(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  bmd(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_setpwm(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)setpwm(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_getpwm(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)getpwm(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_fd(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  fd(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_bk(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  bk(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_motor(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  motor(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_off(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  off(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_alloff(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  alloff();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_ao(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ao();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_enable_1servo(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  enable_servo(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_disable_1servo(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  disable_servo(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_enable_1servos(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  enable_servos();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_disable_1servos(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  disable_servos();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1servo_1enabled(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  set_servo_enabled(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1servo_1enabled(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_servo_enabled(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1servo_1position(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_servo_position(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1servo_1position(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  set_servo_position(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1a_1button_1text(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  set_a_button_text((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1b_1button_1text(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  set_b_button_text((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1c_1button_1text(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  set_c_button_text((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1x_1button_1text(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  set_x_button_text((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1y_1button_1text(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  set_y_button_text((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1z_1button_1text(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  set_z_button_text((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_a_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)a_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_b_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)b_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_c_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)c_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_x_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)x_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_y_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)y_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_z_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)z_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_side_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)side_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_black_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)black_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_a_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)a_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_b_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)b_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_c_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)c_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_x_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)x_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_y_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)y_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_z_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)z_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_side_1button_1clicked(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)side_button_clicked();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_any_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)any_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_extra_1buttons_1show(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  extra_buttons_show();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_extra_1buttons_1hide(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  extra_buttons_hide();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1extra_1buttons_1visible(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_extra_buttons_visible();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1extra_1buttons_1visible(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_extra_buttons_visible(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_digital(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)digital(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1digital_1value(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  set_digital_value(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1digital_1value(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_digital_value(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1digital_1output(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  set_digital_output(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1digital_1output(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_digital_output(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1digital_1pullup(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_digital_pullup(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1digital_1pullup(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  set_digital_pullup(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_pixel_1r_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct pixel **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->r = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_pixel_1r_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct pixel *arg1 = (struct pixel *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct pixel **)&jarg1; 
  result = (int) ((arg1)->r);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_pixel_1g_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct pixel **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->g = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_pixel_1g_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct pixel *arg1 = (struct pixel *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct pixel **)&jarg1; 
  result = (int) ((arg1)->g);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_pixel_1b_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct pixel **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->b = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_pixel_1b_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct pixel *arg1 = (struct pixel *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct pixel **)&jarg1; 
  result = (int) ((arg1)->b);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_new_1pixel(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct pixel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct pixel *)calloc(1, sizeof(struct pixel));
  *(struct pixel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_delete_1pixel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct pixel **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_camera_1open(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  enum Resolution arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum Resolution)jarg1; 
  result = (int)camera_open(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_camera_1open_1device(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  enum Resolution arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (enum Resolution)jarg2; 
  result = (int)camera_open_device(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_camera_1load_1config(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)camera_load_config((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1camera_1width(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_camera_width(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1camera_1height(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_camera_height(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1camera_1width(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_camera_width();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1camera_1height(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_camera_height();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_camera_1update(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)camera_update();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1camera_1pixel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  point2 arg1 ;
  point2 *argp1 ;
  pixel result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(point2 **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null point2");
    return 0;
  }
  arg1 = *argp1; 
  result = get_camera_pixel(arg1);
  {
    pixel * resultptr = (pixel *) malloc(sizeof(pixel));
    memmove(resultptr, &result, sizeof(pixel));
    *(pixel **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1channel_1count(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_channel_count();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1count(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_object_count(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1data(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jstring jresult = 0 ;
  int arg1 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)get_object_data(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1code_1num(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)get_code_num(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1data_1length(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)get_object_data_length(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1confidence(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jdouble jresult = 0 ;
  int arg1 ;
  int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (double)get_object_confidence(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1area(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)get_object_area(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1bbox(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  rectangle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = get_object_bbox(arg1,arg2);
  {
    rectangle * resultptr = (rectangle *) malloc(sizeof(rectangle));
    memmove(resultptr, &result, sizeof(rectangle));
    *(rectangle **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1centroid(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  point2 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = get_object_centroid(arg1,arg2);
  {
    point2 * resultptr = (point2 *) malloc(sizeof(point2));
    memmove(resultptr, &result, sizeof(point2));
    *(point2 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1object_1center(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  point2 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = get_object_center(arg1,arg2);
  {
    point2 * resultptr = (point2 *) malloc(sizeof(point2));
    memmove(resultptr, &result, sizeof(point2));
    *(point2 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_camera_1close(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  camera_close();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_point2_1x_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct point2 **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_point2_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct point2 *arg1 = (struct point2 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct point2 **)&jarg1; 
  result = (int) ((arg1)->x);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_point2_1y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct point2 **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_point2_1y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct point2 *arg1 = (struct point2 *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct point2 **)&jarg1; 
  result = (int) ((arg1)->y);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_new_1point2(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct point2 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct point2 *)calloc(1, sizeof(struct point2));
  *(struct point2 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_delete_1point2(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct point2 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1ulx_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ulx = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1ulx_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  result = (int) ((arg1)->ulx);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1uly_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->uly = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1uly_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  result = (int) ((arg1)->uly);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1width_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1width_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  result = (int) ((arg1)->width);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1height_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_rectangle_1height_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct rectangle **)&jarg1; 
  result = (int) ((arg1)->height);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_new_1rectangle(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct rectangle *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct rectangle *)calloc(1, sizeof(struct rectangle));
  *(struct rectangle **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_delete_1rectangle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct rectangle **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1point2(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  point2 result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = create_point2(arg1,arg2);
  {
    point2 * resultptr = (point2 *) malloc(sizeof(point2));
    memmove(resultptr, &result, sizeof(point2));
    *(point2 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1rectangle(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  rectangle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = create_rectangle(arg1,arg2,arg3,arg4);
  {
    rectangle * resultptr = (rectangle *) malloc(sizeof(rectangle));
    memmove(resultptr, &result, sizeof(rectangle));
    *(rectangle **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_accel_1x(JNIEnv *jenv, jclass jcls) {
  jshort jresult = 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  result = (short)accel_x();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_accel_1y(JNIEnv *jenv, jclass jcls) {
  jshort jresult = 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  result = (short)accel_y();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_accel_1z(JNIEnv *jenv, jclass jcls) {
  jshort jresult = 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  result = (short)accel_z();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_accel_1calibrate(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)accel_calibrate();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_analog10(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)analog10(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_analog(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)analog(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1analog_1pullup(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  set_analog_pullup(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1analog_1pullup(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)get_analog_pullup(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_battery_1charging(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)battery_charging();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_power_1level(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)power_level();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_shut_1down_1in(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  double arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  shut_down_in(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_wait_1for_1light(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  wait_for_light(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_console_1clear(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  console_clear();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1connect(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)create_connect();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1disconnect(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_disconnect();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1start(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_start();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1passive(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_passive();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1safe(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_safe();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1full(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_full();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1spot(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_spot();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1cover(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_cover();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1demo(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_demo(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1cover_1dock(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_cover_dock();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1mode(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_mode();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1lbump(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_lbump();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1rbump(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_rbump();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1lwdrop(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_lwdrop();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1cwdrop(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_cwdrop();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1rwdrop(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_rwdrop();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1wall(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_wall();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1lcliff(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_lcliff();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1lfcliff(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_lfcliff();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1rfcliff(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_rfcliff();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1rcliff(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_rcliff();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1vwall(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_vwall();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1overcurrents(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_overcurrents();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1infrared(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_infrared();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1advance_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_advance_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1play_1button(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_play_button();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1normalized_1angle(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_normalized_angle();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1create_1normalized_1angle(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_create_normalized_angle(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1total_1angle(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_total_angle();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1create_1total_1angle(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_create_total_angle(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1distance(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_distance();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1create_1distance(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_create_distance(arg1);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1battery_1charging_1state(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_battery_charging_state();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1battery_1voltage(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_battery_voltage();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1battery_1current(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_battery_current();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1battery_1temp(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_battery_temp();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1battery_1charge(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_battery_charge();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1battery_1capacity(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_battery_capacity();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1wall_1amt(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_wall_amt();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1lcliff_1amt(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_lcliff_amt();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1lfcliff_1amt(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_lfcliff_amt();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1rfcliff_1amt(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_rfcliff_amt();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1rcliff_1amt(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_rcliff_amt();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1bay_1DI(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_bay_DI();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1bay_1AI(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_bay_AI();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1song_1number(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_song_number();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1song_1playing(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_song_playing();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1number_1of_1stream_1packets(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_number_of_stream_packets();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1requested_1velocity(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_requested_velocity();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1requested_1radius(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_requested_radius();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1requested_1_1right_1velocity(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_requested__right_velocity();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_get_1create_1requested_1left_1velocity(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)get_create_requested_left_velocity();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1stop(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  create_stop();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1drive(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  create_drive(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1drive_1straight(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_drive_straight(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1spin_1CW(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_spin_CW(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1spin_1CCW(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_spin_CCW(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1drive_1direct(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  create_drive_direct(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1advance_1led(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_advance_led(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1play_1led(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_play_led(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1power_1led(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  create_power_led(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1load_1song(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_load_song(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_create_1play_1song(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  create_play_song(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1remove_1category(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  datalog_remove_category((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1append_1string(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  datalog_append_string((char const *)arg1,(char const *)arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1append_1number(JNIEnv *jenv, jclass jcls, jdouble jarg1, jstring jarg2) {
  double arg1 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  datalog_append_number(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1remove(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  datalog_remove(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1write_1plain(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)datalog_write_plain((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1write_1csv(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)datalog_write_csv((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_datalog_1clear(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  datalog_clear();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_debug_1print_1registers(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  debug_print_registers();
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_register_1value(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  unsigned short arg1 ;
  unsigned short result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned short)jarg1; 
  result = (unsigned short)register_value(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_debug_1dump_1data(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) (unsigned char *)0 ;
  size_t arg2 ;
  char *arg3 = (char *) (char *)0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(unsigned char **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)debug_dump_data((unsigned char const *)arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_display_1clear(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  display_clear();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_display_1printf(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jstring jarg3) {
  int arg1 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  void *arg4 = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  display_printf(arg1,arg2,(char const *)arg3,arg4);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT jint JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_draw_1open(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)draw_open();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_draw_1point(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  draw_point(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_draw_1line(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jint jarg4) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  draw_line(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_draw_1clear(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  draw_clear();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_draw_1close(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  draw_close();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_set_1auto_1publish(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  set_auto_publish(arg1);
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_publish(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  publish();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_halt(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  halt();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_freeze_1halt(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  freeze_halt();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_ir_1read(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ir_read();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_ir_1write(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  ir_write();
}


SWIGEXPORT void JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_msleep(JNIEnv *jenv, jclass jcls, jint jarg1) {
  long arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (long)jarg1; 
  msleep(arg1);
}


SWIGEXPORT jlong JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_systime(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  unsigned long result;
  
  (void)jenv;
  (void)jcls;
  result = (unsigned long)systime();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_linkjvm_libkovan_jni_LinkJVMJNI_seconds(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)seconds();
  jresult = (jdouble)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

