/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.camera;

public class Device {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Device(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_cameraJNI.delete_Device(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Device(InputProvider inputProvider) {
    this(linkjvm_cameraJNI.new_Device(InputProvider.getCPtr(inputProvider), inputProvider), true);
  }

  public boolean open(int number) {
    return linkjvm_cameraJNI.Device_open__SWIG_0(swigCPtr, this, number);
  }

  public boolean open() {
    return linkjvm_cameraJNI.Device_open__SWIG_1(swigCPtr, this);
  }

  public boolean isOpen() {
    return linkjvm_cameraJNI.Device_isOpen(swigCPtr, this);
  }

  public boolean close() {
    return linkjvm_cameraJNI.Device_close(swigCPtr, this);
  }

  public boolean update() {
    return linkjvm_cameraJNI.Device_update(swigCPtr, this);
  }

  public void setWidth(long width) {
    linkjvm_cameraJNI.Device_setWidth(swigCPtr, this, width);
  }

  public void setHeight(long height) {
    linkjvm_cameraJNI.Device_setHeight(swigCPtr, this, height);
  }

  public long width() {
    return linkjvm_cameraJNI.Device_width(swigCPtr, this);
  }

  public long height() {
    return linkjvm_cameraJNI.Device_height(swigCPtr, this);
  }

  public ChannelVector channels() {
    return new ChannelVector(linkjvm_cameraJNI.Device_channels(swigCPtr, this), false);
  }

  public InputProvider inputProvider() {
    long cPtr = linkjvm_cameraJNI.Device_inputProvider(swigCPtr, this);
    return (cPtr == 0) ? null : new InputProvider(cPtr, false);
  }

  public SWIGTYPE_p_cv__Mat rawImage() {
    return new SWIGTYPE_p_cv__Mat(linkjvm_cameraJNI.Device_rawImage(swigCPtr, this), false);
  }

  public void setConfig(Config config) {
    linkjvm_cameraJNI.Device_setConfig(swigCPtr, this, Config.getCPtr(config), config);
  }

  public Config config() {
    return new Config(linkjvm_cameraJNI.Device_config(swigCPtr, this), false);
  }

  public void setChannelImplManager(ChannelImplManager channelImplManager) {
    linkjvm_cameraJNI.Device_setChannelImplManager(swigCPtr, this, ChannelImplManager.getCPtr(channelImplManager), channelImplManager);
  }

  public ChannelImplManager channelImplManager() {
    long cPtr = linkjvm_cameraJNI.Device_channelImplManager(swigCPtr, this);
    return (cPtr == 0) ? null : new ChannelImplManager(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char bgr() {
    long cPtr = linkjvm_cameraJNI.Device_bgr(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

}
