/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.jni.camera;

public interface linkjvm_cameraConstants {
  public final static String CAMERA_GROUP = linkjvm_cameraJNI.CAMERA_GROUP_get();
  public final static String CAMERA_NUM_CHANNELS_KEY = linkjvm_cameraJNI.CAMERA_NUM_CHANNELS_KEY_get();
  public final static String CAMERA_CHANNEL_GROUP_PREFIX = linkjvm_cameraJNI.CAMERA_CHANNEL_GROUP_PREFIX_get();
  public final static String CAMERA_CHANNEL_TYPE_KEY = linkjvm_cameraJNI.CAMERA_CHANNEL_TYPE_KEY_get();
  public final static String CAMERA_CHANNEL_TYPE_HSV_KEY = linkjvm_cameraJNI.CAMERA_CHANNEL_TYPE_HSV_KEY_get();
  public final static String CAMERA_CHANNEL_TYPE_QR_KEY = linkjvm_cameraJNI.CAMERA_CHANNEL_TYPE_QR_KEY_get();
}
