/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.libkovan.jni;

public class pixel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pixel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pixel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkJVMJNI.delete_pixel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(int value) {
    LinkJVMJNI.pixel_r_set(swigCPtr, this, value);
  }

  public int getR() {
    return LinkJVMJNI.pixel_r_get(swigCPtr, this);
  }

  public void setG(int value) {
    LinkJVMJNI.pixel_g_set(swigCPtr, this, value);
  }

  public int getG() {
    return LinkJVMJNI.pixel_g_get(swigCPtr, this);
  }

  public void setB(int value) {
    LinkJVMJNI.pixel_b_set(swigCPtr, this, value);
  }

  public int getB() {
    return LinkJVMJNI.pixel_b_get(swigCPtr, this);
  }

  public pixel() {
    this(LinkJVMJNI.new_pixel(), true);
  }

}
