/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.camera;

public class Config {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_cameraJNI.delete_Config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Config() {
    this(linkjvm_cameraJNI.new_Config__SWIG_0(), true);
  }

  public Config(SWIGTYPE_p_std__mapT_std__string_std__string_t config) {
    this(linkjvm_cameraJNI.new_Config__SWIG_1(SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(config)), true);
  }

  public static Config load(SWIGTYPE_p_std__string path) {
    long cPtr = linkjvm_cameraJNI.Config_load(SWIGTYPE_p_std__string.getCPtr(path));
    return (cPtr == 0) ? null : new Config(cPtr, false);
  }

  public boolean save(SWIGTYPE_p_std__string path) {
    return linkjvm_cameraJNI.Config_save(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(path));
  }

  public void beginGroup(SWIGTYPE_p_std__string group) {
    linkjvm_cameraJNI.Config_beginGroup(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(group));
  }

  public void endGroup() {
    linkjvm_cameraJNI.Config_endGroup(swigCPtr, this);
  }

  public void clearGroup() {
    linkjvm_cameraJNI.Config_clearGroup(swigCPtr, this);
  }

  public void clear() {
    linkjvm_cameraJNI.Config_clear(swigCPtr, this);
  }

  public boolean containsKey(SWIGTYPE_p_std__string key) {
    return linkjvm_cameraJNI.Config_containsKey(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key));
  }

  public boolean boolValue(SWIGTYPE_p_std__string key) {
    return linkjvm_cameraJNI.Config_boolValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key));
  }

  public int intValue(SWIGTYPE_p_std__string key) {
    return linkjvm_cameraJNI.Config_intValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key));
  }

  public double doubleValue(SWIGTYPE_p_std__string key) {
    return linkjvm_cameraJNI.Config_doubleValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key));
  }

  public SWIGTYPE_p_std__string stringValue(SWIGTYPE_p_std__string key) {
    return new SWIGTYPE_p_std__string(linkjvm_cameraJNI.Config_stringValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key)), true);
  }

  public void setValue(SWIGTYPE_p_std__string key, boolean value) {
    linkjvm_cameraJNI.Config_setValue__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key), value);
  }

  public void setValue(SWIGTYPE_p_std__string key, int value) {
    linkjvm_cameraJNI.Config_setValue__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key), value);
  }

  public void setValue(SWIGTYPE_p_std__string key, double value) {
    linkjvm_cameraJNI.Config_setValue__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key), value);
  }

  public void setValue(SWIGTYPE_p_std__string key, String value) {
    linkjvm_cameraJNI.Config_setValue__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key), value);
  }

  public void setValue(SWIGTYPE_p_std__string key, SWIGTYPE_p_std__string value) {
    linkjvm_cameraJNI.Config_setValue__SWIG_4(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(key), SWIGTYPE_p_std__string.getCPtr(value));
  }

  public Config values() {
    return new Config(linkjvm_cameraJNI.Config_values(swigCPtr, this), true);
  }

  public void addValues(Config config) {
    linkjvm_cameraJNI.Config_addValues(swigCPtr, this, Config.getCPtr(config), config);
  }

}
