/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.camera;

public class linkjvm_camera implements linkjvm_cameraConstants {
  public static Device cDevice() {
    long cPtr = linkjvm_cameraJNI.cDevice();
    return (cPtr == 0) ? null : new Device(cPtr, false);
  }

}
