/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.camera;

public class UnsignedIntRect2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UnsignedIntRect2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedIntRect2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_cameraJNI.delete_UnsignedIntRect2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedIntRect2(long x, long y, long width, long height) {
    this(linkjvm_cameraJNI.new_UnsignedIntRect2(x, y, width, height), true);
  }

  public long x() {
    return linkjvm_cameraJNI.UnsignedIntRect2_x(swigCPtr, this);
  }

  public long y() {
    return linkjvm_cameraJNI.UnsignedIntRect2_y(swigCPtr, this);
  }

  public long width() {
    return linkjvm_cameraJNI.UnsignedIntRect2_width(swigCPtr, this);
  }

  public long height() {
    return linkjvm_cameraJNI.UnsignedIntRect2_height(swigCPtr, this);
  }

  public UnsignedIntPoint2 center() {
    return new UnsignedIntPoint2(linkjvm_cameraJNI.UnsignedIntRect2_center(swigCPtr, this), true);
  }

  public void setX(long x) {
    linkjvm_cameraJNI.UnsignedIntRect2_setX(swigCPtr, this, x);
  }

  public void setY(long y) {
    linkjvm_cameraJNI.UnsignedIntRect2_setY(swigCPtr, this, y);
  }

  public void setWidth(long width) {
    linkjvm_cameraJNI.UnsignedIntRect2_setWidth(swigCPtr, this, width);
  }

  public void setHeight(long height) {
    linkjvm_cameraJNI.UnsignedIntRect2_setHeight(swigCPtr, this, height);
  }

  public long area() {
    return linkjvm_cameraJNI.UnsignedIntRect2_area(swigCPtr, this);
  }

  public rectangle toCRectangle() {
    return new rectangle(linkjvm_cameraJNI.UnsignedIntRect2_toCRectangle(swigCPtr, this), true);
  }

}
