/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package linkjvm.low.camera;

public class UnsignedIntPoint2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UnsignedIntPoint2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedIntPoint2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        linkjvm_cameraJNI.delete_UnsignedIntPoint2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedIntPoint2(long x, long y) {
    this(linkjvm_cameraJNI.new_UnsignedIntPoint2(x, y), true);
  }

  public long x() {
    return linkjvm_cameraJNI.UnsignedIntPoint2_x(swigCPtr, this);
  }

  public long y() {
    return linkjvm_cameraJNI.UnsignedIntPoint2_y(swigCPtr, this);
  }

  public void setX(long x) {
    linkjvm_cameraJNI.UnsignedIntPoint2_setX(swigCPtr, this, x);
  }

  public void setY(long y) {
    linkjvm_cameraJNI.UnsignedIntPoint2_setY(swigCPtr, this, y);
  }

  public point2 toCPoint2() {
    return new point2(linkjvm_cameraJNI.UnsignedIntPoint2_toCPoint2(swigCPtr, this), true);
  }

}
